import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ApolloSetting from "@/commons/settings/apollo-setting";
import Layout from "@/commons/layout";
import ApolloUploadSetting from "@/commons/settings/apollo-setting";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Iprops {
  children: React.ReactNode;
}
export default function RootLayout({ children }: Iprops) {
  return (
    <html lang="en">
      <body>
        {/* 상단 레이아웃 표시용 */}
        <div className="w-full text-center py-2 bg-gray-100">
          ======레이아웃 윗부분=======
        </div>

        {/* ApolloProvider + 중앙 정렬 Layout */}
        <ApolloUploadSetting>
          <Layout>
            <div className="w-full flex justify-center">
              <div className="w-full max-w-7xl px-4 flex flex-col items-center">
                {children}
              </div>
            </div>
          </Layout>
        </ApolloUploadSetting>

        {/* 하단 레이아웃 표시용 */}
        <div className="w-full text-center py-2 bg-gray-100">
          ======레이아웃 아랫부분======
        </div>
      </body>
    </html>
  );
}
