import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ApolloSetting from "@/commons/settings/apollo-setting";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Iprops {
  children: React.ReactNode;
}
export default function RootLayout(props: Iprops) {
  return (
    <html lang="en">
      <body
        className={`max-w-7xl  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>======레이아웃 윗부분=======</div>
        <ApolloSetting children={props.children} />
        <div>======레이아웃 아랫부분======</div>
      </body>
    </html>
  );
}
